version: '2.2'


services:
  app:
    build: .
    container_name: "heinz-bot"
    restart: unless-stopped
    volumes:
      - .:/var/www/htdocs
      - ./log:/var/www/htdocs/log
    network_mode: "host"
    command: /bin/sh -c "/var/www/htdocs/debug.sh"
