version: '2.2'


services:
  app:
    build: .
    container_name: "heinz-bot"
    restart: unless-stopped
    volumes:
      - .:/var/www/htdocs
    network_mode: "host"
    command: /bin/sh -c "/var/www/htdocs/debug.sh"
    #command: tail -f /dev/null