version: '2.2'

volumes:
  heinz-db:

services:
  app:
    build: .
    container_name: "heinz-bot"
    restart: unless-stopped
    volumes:
      - .:/var/www/htdocs
    network_mode: "host"
    command: /bin/sh -c "/var/www/htdocs/debug.sh"
    #command: tail -f /dev/null

  db:
    image: mysql
    container_name: "heinz-db"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - heinz-db:/var/lib/mysql
    ports:
      - "3306:3306"