version: '2.2'

networks:
  web:
    external: true

volumes:
  python-app:
  heinz-db:

services:
  app:
    build: .
    container_name: "heinz-bot"
    restart: unless-stopped
    volumes:
      - .:/var/www/htdocs
      - ./log:/var/www/htdocs/log
    networks:
      - web
    command: python3 heinz_bot.py
    #command: tail -f /dev/null

  db:
    image: mysql
    container_name: "heinz-db"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - heinz-db:/var/lib/mysql
    networks:
      - web