version: '2.2'

networks:
  web:
    external: true

volumes:
  python-app:

services:
  app:
    build: .
    container_name: "heinz-bot"
    restart: unless-stopped
    volumes:
      - .:/var/www/htdocs
    networks:
      - web
