# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import microservices.media_service.entpb_pb2 as entpb__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MediaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            '/entpb.MediaService/Create',
            request_serializer=entpb__pb2.CreateMediaRequest.SerializeToString,
            response_deserializer=entpb__pb2.Media.FromString,
        )
        self.Get = channel.unary_unary(
            '/entpb.MediaService/Get',
            request_serializer=entpb__pb2.GetMediaRequest.SerializeToString,
            response_deserializer=entpb__pb2.Media.FromString,
        )
        self.Delete = channel.unary_unary(
            '/entpb.MediaService/Delete',
            request_serializer=entpb__pb2.DeleteMediaRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.List = channel.unary_unary(
            '/entpb.MediaService/List',
            request_serializer=entpb__pb2.ListMediaRequest.SerializeToString,
            response_deserializer=entpb__pb2.ListMediaResponse.FromString,
        )


class MediaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Create': grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=entpb__pb2.CreateMediaRequest.FromString,
            response_serializer=entpb__pb2.Media.SerializeToString,
        ),
        'Get': grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=entpb__pb2.GetMediaRequest.FromString,
            response_serializer=entpb__pb2.Media.SerializeToString,
        ),
        'Delete': grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=entpb__pb2.DeleteMediaRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'List': grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=entpb__pb2.ListMediaRequest.FromString,
            response_serializer=entpb__pb2.ListMediaResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'entpb.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(request, target, '/entpb.MediaService/Create',
                                             entpb__pb2.CreateMediaRequest.SerializeToString,
                                             entpb__pb2.Media.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/entpb.MediaService/Get',
                                             entpb__pb2.GetMediaRequest.SerializeToString,
                                             entpb__pb2.Media.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(request, target, '/entpb.MediaService/Delete',
                                             entpb__pb2.DeleteMediaRequest.SerializeToString,
                                             google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/entpb.MediaService/List',
                                             entpb__pb2.ListMediaRequest.SerializeToString,
                                             entpb__pb2.ListMediaResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
